name: .NET Core Console CI

 

on:

  push:

    branches: [ "main" ]

  pull_request:

    branches: [ "main" ]

 

jobs:

  build-and-test:

 

    name: build-and-test-${{matrix.os}}

    runs-on: ${{ matrix.os }}

    strategy:

      matrix:

        os: [windows-latest]

       

    env:

      Solution_Name: lab_7/Laws_Brody_Lab_5.sln

      Test_Project_Path: lab_7_testing/Lab_5_Testing.csproj

 

    steps:

    - name: Checkout repository

      uses: actions/checkout@v4

 

    - name: Install .NET Core

      uses: actions/setup-dotnet@v4

      with:

        dotnet-version: '8.0.x'

 

    - name: Restore NuGet packages

      run: dotnet restore ${{ env.Solution_Name }}

 

    - name: Build solution

      run: dotnet build ${{ env.Solution_Name }} --configuration Release --no-restore

 

    - name: Test and publish results

      run: |

        dotnet test ${{ env.Test_Project_Path }} --no-restore --verbosity normal

 
